/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MyBookingsRouteImport } from './routes/my-bookings'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as EventsIndexRouteImport } from './routes/events.index'
import { Route as OrganizerDashboardRouteImport } from './routes/organizer.dashboard'
import { Route as TicketsIdRouteImport } from './routes/tickets.$id'
import { Route as EventsIdIndexRouteImport } from './routes/events.$id.index'
import { Route as EventsIdBookingRouteImport } from './routes/events.$id.booking'
import { Route as OrganizerEventsIndexRouteImport } from './routes/organizer.events.index'
import { Route as OrganizerEventsCreateRouteImport } from './routes/organizer.events.create'
import { Route as OrganizerEventsIdEditRouteImport } from './routes/organizer.events.$id.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MyBookingsRoute = MyBookingsRouteImport.update({
  id: '/my-bookings',
  path: '/my-bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizerDashboardRoute = OrganizerDashboardRouteImport.update({
  id: '/organizer/dashboard',
  path: '/organizer/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsIdRoute = TicketsIdRouteImport.update({
  id: '/tickets/$id',
  path: '/tickets/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIdIndexRoute = EventsIdIndexRouteImport.update({
  id: '/events/$id/',
  path: '/events/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIdBookingRoute = EventsIdBookingRouteImport.update({
  id: '/events/$id/booking',
  path: '/events/$id/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizerEventsIndexRoute = OrganizerEventsIndexRouteImport.update({
  id: '/organizer/events/',
  path: '/organizer/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizerEventsCreateRoute = OrganizerEventsCreateRouteImport.update({
  id: '/organizer/events/create',
  path: '/organizer/events/create',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizerEventsIdEditRoute = OrganizerEventsIdEditRouteImport.update({
  id: '/organizer/events/$id/edit',
  path: '/organizer/events/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/my-bookings': typeof MyBookingsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/organizer/dashboard': typeof OrganizerDashboardRoute
  '/tickets/$id': typeof TicketsIdRoute
  '/events/': typeof EventsIndexRoute
  '/events/$id/booking': typeof EventsIdBookingRoute
  '/organizer/events/create': typeof OrganizerEventsCreateRoute
  '/events/$id/': typeof EventsIdIndexRoute
  '/organizer/events/': typeof OrganizerEventsIndexRoute
  '/organizer/events/$id/edit': typeof OrganizerEventsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/my-bookings': typeof MyBookingsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/organizer/dashboard': typeof OrganizerDashboardRoute
  '/tickets/$id': typeof TicketsIdRoute
  '/events': typeof EventsIndexRoute
  '/events/$id/booking': typeof EventsIdBookingRoute
  '/organizer/events/create': typeof OrganizerEventsCreateRoute
  '/events/$id': typeof EventsIdIndexRoute
  '/organizer/events': typeof OrganizerEventsIndexRoute
  '/organizer/events/$id/edit': typeof OrganizerEventsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/my-bookings': typeof MyBookingsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/organizer/dashboard': typeof OrganizerDashboardRoute
  '/tickets/$id': typeof TicketsIdRoute
  '/events/': typeof EventsIndexRoute
  '/events/$id/booking': typeof EventsIdBookingRoute
  '/organizer/events/create': typeof OrganizerEventsCreateRoute
  '/events/$id/': typeof EventsIdIndexRoute
  '/organizer/events/': typeof OrganizerEventsIndexRoute
  '/organizer/events/$id/edit': typeof OrganizerEventsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checkout'
    | '/login'
    | '/my-bookings'
    | '/profile'
    | '/register'
    | '/organizer/dashboard'
    | '/tickets/$id'
    | '/events/'
    | '/events/$id/booking'
    | '/organizer/events/create'
    | '/events/$id/'
    | '/organizer/events/'
    | '/organizer/events/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout'
    | '/login'
    | '/my-bookings'
    | '/profile'
    | '/register'
    | '/organizer/dashboard'
    | '/tickets/$id'
    | '/events'
    | '/events/$id/booking'
    | '/organizer/events/create'
    | '/events/$id'
    | '/organizer/events'
    | '/organizer/events/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/checkout'
    | '/login'
    | '/my-bookings'
    | '/profile'
    | '/register'
    | '/organizer/dashboard'
    | '/tickets/$id'
    | '/events/'
    | '/events/$id/booking'
    | '/organizer/events/create'
    | '/events/$id/'
    | '/organizer/events/'
    | '/organizer/events/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckoutRoute: typeof CheckoutRoute
  LoginRoute: typeof LoginRoute
  MyBookingsRoute: typeof MyBookingsRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  OrganizerDashboardRoute: typeof OrganizerDashboardRoute
  TicketsIdRoute: typeof TicketsIdRoute
  EventsIndexRoute: typeof EventsIndexRoute
  EventsIdBookingRoute: typeof EventsIdBookingRoute
  OrganizerEventsCreateRoute: typeof OrganizerEventsCreateRoute
  EventsIdIndexRoute: typeof EventsIdIndexRoute
  OrganizerEventsIndexRoute: typeof OrganizerEventsIndexRoute
  OrganizerEventsIdEditRoute: typeof OrganizerEventsIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-bookings': {
      id: '/my-bookings'
      path: '/my-bookings'
      fullPath: '/my-bookings'
      preLoaderRoute: typeof MyBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizer/dashboard': {
      id: '/organizer/dashboard'
      path: '/organizer/dashboard'
      fullPath: '/organizer/dashboard'
      preLoaderRoute: typeof OrganizerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets/$id': {
      id: '/tickets/$id'
      path: '/tickets/$id'
      fullPath: '/tickets/$id'
      preLoaderRoute: typeof TicketsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$id/': {
      id: '/events/$id/'
      path: '/events/$id'
      fullPath: '/events/$id/'
      preLoaderRoute: typeof EventsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$id/booking': {
      id: '/events/$id/booking'
      path: '/events/$id/booking'
      fullPath: '/events/$id/booking'
      preLoaderRoute: typeof EventsIdBookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizer/events/': {
      id: '/organizer/events/'
      path: '/organizer/events'
      fullPath: '/organizer/events/'
      preLoaderRoute: typeof OrganizerEventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizer/events/create': {
      id: '/organizer/events/create'
      path: '/organizer/events/create'
      fullPath: '/organizer/events/create'
      preLoaderRoute: typeof OrganizerEventsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizer/events/$id/edit': {
      id: '/organizer/events/$id/edit'
      path: '/organizer/events/$id/edit'
      fullPath: '/organizer/events/$id/edit'
      preLoaderRoute: typeof OrganizerEventsIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckoutRoute: CheckoutRoute,
  LoginRoute: LoginRoute,
  MyBookingsRoute: MyBookingsRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  OrganizerDashboardRoute: OrganizerDashboardRoute,
  TicketsIdRoute: TicketsIdRoute,
  EventsIndexRoute: EventsIndexRoute,
  EventsIdBookingRoute: EventsIdBookingRoute,
  OrganizerEventsCreateRoute: OrganizerEventsCreateRoute,
  EventsIdIndexRoute: EventsIdIndexRoute,
  OrganizerEventsIndexRoute: OrganizerEventsIndexRoute,
  OrganizerEventsIdEditRoute: OrganizerEventsIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
